### 머신러닝 수행 순서
* 데이터 불러오기(파일.db)
* 머신러닝에 적합한 형태로 전처리
* 데이터셋 분리(학습용, 검증용)
* 라이브러리 임포트(모델)
* 모델 객체 생성
* 학습
* 

### scikit-learn(사이킷런)
* anaconda에 포함
* 모델 import
* 객체=모델(): 객체 생성
* fit(): 학습
* 객체.predict(): 예측

In [5]:
from sklearn import svm
model = svm.SVC()
xor_data = [
    [0,0,0],
    [0,1,1],
    [1,0,1],
    [1,1,0]
    
]

In [6]:
# 학습
# fit(독립변수, 종속변수)
model.fit([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
    
], [0,1,1,0])

SVC()

In [7]:
# 예측
model.predict([[0,0]])

array([0])

In [12]:
# 학습데이터에서 결과값을 분리
data = []
label = []
for r in xor_data:
    data.append([r[0], r[1]])
    label.append(r[2])
    

In [13]:
model.fit(data, label)

SVC()

In [14]:
pre = model.predict(data)
pre

array([0, 1, 1, 0])

In [15]:
cnt = 0
for i, a in enumerate(label):
    if a == pre[i]:
        cnt +=1
print('정답률:{}'.format(cnt/len(label)))

정답률:1.0


In [16]:
import numpy as np

In [18]:
x = np.arange(10).reshape(-1,1)
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
def f(x):
    return 2*x+1
y= f(x)
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [20]:
# 선형회귀모델
from sklearn.linear_model import LinearRegression

In [21]:
model = LinearRegression() # 객체 생성
model.fit(x, y)

LinearRegression()

In [24]:
pre = model.predict([[10], [20]])
pre

array([[21.],
       [41.]])

In [25]:
## 키와, 몸무게 랜덤으로 구해서 bmi 구해 csv저장

In [31]:
# bmi 구하는 함수
# 결과값은 0:저체중, 1:표준, 2:과체중
def bmi(h,w):
    v = w/(h/100)**2
    if v <18.5:
        return 0
    elif v <25:
        return 1
    else :
        return 2
f = open('bmi.csv', 'w', encoding='utf-8')
f.write('height, weight, label\n')
for i in range(100):
    import random
    h = random.randint(120,210) # 키
    w = random.randint(30,100) # 몸무게
    label = bmi(h,w)
    f.write('{0},{1},{2}\n'.format(h,w,label))
f.close()

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('bmi.csv')
df.head()

height   weight   label
0     142      100       2
1     172       75       2
2     121       40       2
3     134       64       2
4     202       73       0

In [33]:
# 산점도
df2 = df[df.loc[:,'label']==1]
plt.scatter(df2['weight'], df2['height'])

KeyError: 'label'

In [34]:
df.iloc[:,:2]

height   weight
0      142      100
1      172       75
2      121       40
3      134       64
4      202       73
..     ...      ...
95     184       51
96     121       55
97     153       35
98     167       56
99     144       75

[100 rows x 2 columns]

In [42]:
# 학습데이터와 검증데이터 분리
from sklearn.model_selection import train_test_split
# train_test_split()
# 리턴값: 학습용데이터, 검증용데이터, 학습용답, 검증용답
data_train, data_test, label_train, label_test = train_test_split\
(df.iloc[:,:2],df['label'], random_state=10)

KeyError: 'label'

In [39]:
data_train.shape, data_test.shape

NameError: name 'data_train' is not defined

In [40]:
# import
from sklrean import svm, metrics
model = svm.SVC()
model.fit(data_train, label_train)
pred = model.predict(data_test)

ModuleNotFoundError: No module named 'sklrean'

In [41]:
# 평가
score = metrics.accruacy_score(label_test, pred)
score

NameError: name 'metrics' is not defined