In [1]:
# 텐서플로 설치
!pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=575f4036f9e8305196d9449b6495960b2169f363e186479d5d8437c6b5a4da23
  Stored in directory: c:\users\sundooedu\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
  Created wheel for wrapt: filename=wrapt-1.12.1-cp38-cp38-win_amd64.whl size=33737 sha256=d1ed22bdce0a87b4b5bcc2b473f156d07705c85b623b12efd62dfe945884b6a1
  Stored in directory: c:\users\sundooedu\appdata\local\pip\cache\wheels\5f\fd\9e\b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73
Successfully built termcolor wrapt
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.11.2
    Uninstalling wrapt-1.11.2:
      Successfully uninstalled wrapt-1.11.2


In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
# 텐서 생성
a = tf.constant(3)

In [4]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
# 스칼라는 0차원이므로 shape에 값이 안나옴

In [6]:
# 리스트로 생성
b = tf.constant([1,2,3])
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [7]:
# numpy에 출력되는 값이 rank
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
print(tf.rank(b))

tf.Tensor(1, shape=(), dtype=int32)


In [9]:
# 튜플로 생성
c = tf.constant(((1,2),(3,4)))
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [11]:
# numpy array로도 생성
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
d = tf.constant(arr)
d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
d.shape

TensorShape([2, 3])

In [13]:
d.dtype

tf.int32

In [14]:
# 자료형 변환
tf.cast(d, dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [17]:
type(d)

tensorflow.python.framework.ops.EagerTensor

In [16]:
# 텐서를 넘파이어레이로 변환해서 리턴
d.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
e = np.array(d)

In [20]:
type(e)

numpy.ndarray

In [21]:
# 텐서로 변환해주는 메서드
tf.convert_to_tensor(e)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [22]:
# 기본연산
a = tf.constant(20)
b = tf.constant(10)

In [25]:
c = tf.add(a,b)
d = tf.subtract(a,b)
e = tf.multiply(a,b)
c,d,e

(<tf.Tensor: shape=(), dtype=int32, numpy=30>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=200>)

In [26]:
c.numpy(), d.numpy()

(30, 10)

In [27]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

In [28]:
# 브로드캐스팅
a = tf.constant([1,2,3])
b = tf.constant(3)
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>